### ISSUE TITLE
Can't add loot to the table

### ISSUE THREAD

**Issue by scalda** [maruohon/moreloottables#1]
Hi,

I am haveing trouble adding items to the loot tables you mod provides using loottweaker.
I have tried all 3 mobs you add and not one will accept the items. the scripts work as I can apply them to other normal mobs with not trouble.

regards

scalda

**Comment by maruohon** [comment]
I don't know anything about LootTweaker itself. But have you created loot table files for the mobs? I think if vanilla doesn't find the files, then it will fall back to an empty loot table, and LootTweaker probably can't edit them if they use the empty loot table instance.

I'm not entirely sure how exactly this should be done... The loot table paths that I'm registering are searched for from the vanilla locations... I'll try adding dummy loot tables to the mod itself and see if that fixes it.

But I would need a test case. And as I don't know anything about LootTweaker or CraftTweaker and would rather not spend time learning all that stuff, could you provide me all the necessary configs and scripts and a list of the mods that I need to get to test this? Is it just CraftTweaker and LootTweaker and the configs and scripts for those?

**Comment by scalda** [comment]
Ok, loot tweaker can dump the loot tables out which it does and it picks up your new loot tables, but there doesn't seem to be any pools in there for the mobs to pull fro.

I have just made you a quick mod pack for you to import into curse with my loot tweaker script that you can test out against.

Regards

scalda

[Loot table fix-1.0.zip](https://github.com/maruohon/moreloottables/files/858319/Loot.table.fix-1.0.zip)

**Comment by maruohon** [comment]
So does that mean that LootTweaker can't add new pools? I'm not providing any pools or even loot table jsons with the mod, I'm only registering basically loot table locations. I have now been staring at the LootTableManager code, but I don't see any way for me to even provide default loot table files with this system, as it only tries to load them and fires the Forge event if it finds the loot table files in the first place, but it's only searching for them from the world directory and then as a fall-back from the vanilla jar... I'll have to ask some people how this is supposed to work.

**Comment by scalda** [comment]
it can add pools yes, but it doesn't seem to be able to add them to your mods loot tables.

These are mods in our pack that add tables. yours appear under minecraft. so not sure if you can look at their code and work something out.

as I can add and remove from their tables fine

<img src = https://i.gyazo.com/c27f2bb6c304f4d5963235c3c3464948.png>

regards

scalda

**Comment by maruohon** [comment]
Yeah I'm thinking it's probably because it falls back to the EMPTY_LOOT_TABLE for mine, if they haven't been actually added. Could you try creating just empty loot table files inside the world directory of a test world, in `data/loot_tables/minecraft/entities/husk.json` etc. And see if LootTweaker is able to add pools after those dummy files are in place.

Edit: Or maybe they should at least contain the empty pools array.

**Comment by scalda** [comment]
No it adds nothing to those tables

**Comment by maruohon** [comment]
I released a new version, which adds default empty loot tables. In my testing it seemed to fix LootTweaker, and I was able to add loot to the Wither with this:

```ZenScript
val wither = LootTables.getTable("minecraft:entities/boss/wither");
wither.addPool("loot", 3, 64, 0, 0);
val wloot = wither.getPool("loot");
wloot.addItemEntry(<minecraft:nether_star>, 1);
wloot.addItemEntry(<minecraft:stick>, 1);
wloot.addItemEntry(<minecraft:potato>, 1);
```

**Comment by scalda** [comment]
It works, thank you for fixing this for us, I am about to push an update to FoolCraft with this in.

**Comment by maruohon** [comment]
Oh! So THAT is where your name was familiar from... I've only recently started watching through Xisuma's Hermitpack series (due to all my time going to modding related things >_>), and I think your name has popped up in the server chat, heh :)
