### ISSUE TITLE
Loot to mobs

### ISSUE THREAD

**Issue by GWSheridan** [maruohon/moreloottables#2]
Trying to add loot to a mob but i seem to have hit a snag. This what i have tried

import loottweaker.vanilla.loot.LootTables;
import loottweaker.vanilla.loot.LootTable;
import loottweaker.vanilla.loot.LootPool;
import loottweaker.vanilla.loot.Functions;

//add leather
val blazing_juggernautTable = LootTables.getTable("primitivemobs:entities/blazing_juggernaut");
val blazing_juggernautPool = blazing_juggernautTable.addPool("leather", 0, 1, 0, 0);
val leather = <minecraft:leather>;
blazing_juggernautPool.addItemEntry(leather, 1);

Then I tried this way

import loottweaker.vanilla.loot.LootTables;
import loottweaker.vanilla.loot.LootTable;
import loottweaker.vanilla.loot.LootPool;
import loottweaker.vanilla.loot.Functions;

//Value
val blazing_juggernautTable = LootTables.getTable("primitivemobs:entities/blazing_juggernaut");
blazing_juggernaut.addPool("loot", 3, 64, 0, 0);
val blazingloot = blazing_juggernaut.getPool("loot");
blazingloot.addItemEntry(<minecraft:leather>, 1);

**Comment by maruohon** [comment]
Hmm, did you post this issue in the wrong repo? More Loot Tables only adds loot tables to the vanilla mobs that don't have them in vanilla (in 1.12 this only includes the Wither boss).

**Comment by GWSheridan** [comment]
Sorry ye got the same name as another more loot stuff was what i was after

**Comment by maruohon** [comment]
Just a complete guess: shouldn't the name of the item be inside double quotes? Ie. `"minecraft:leather"`.

**Comment by GWSheridan** [comment]
ye i tried that its really confused me

**Comment by GWSheridan** [comment]
i would think its more less same way you would do the Vanilla mobs with moreloottables

**Comment by maruohon** [comment]
Looking at the older issue #1, the names there were in the format `<minecraft:leather>`.

Edit: So that format seems to be specific to Loot Tweaker, so probably because of Craft Tweaker/Mine Tweaker or whatever it's called these days using that format for names, and Loot Tweaker being an addon to that I believe?

**Comment by GWSheridan** [comment]
ye think so thanks for help even though not your mod xD sorry about that

**Comment by maruohon** [comment]
Heh no problem :)
