### ISSUE TITLE
Wither Loot Table Not Being Picked Up

### ISSUE THREAD

**Issue by vizthex123** [maruohon/moreloottables#3]
Title.

My script is this:

```
val wither_boss = loottweaker.LootTweaker.getTable("minecraft:entities/wither");

val wither_boss_loot = wither_boss.addPool("wither_loot", 1, 1, 0, 3);
val nether_star = wither_boss.addPool("nether_star", 1, 1, 0, 0);

wither_boss_loot.addItemEntry(<ordinarycoins:coinplatinum>, 5);
nether_star.addItemEntry(<minecraft:nether_star>, 1);
```

But the game doesn't pick it up. It just says "no table with the name minecraft:entities/wither exists"

**Comment by maruohon** [comment]
It should be at `minecraft/entities/boss/wither`.

**Comment by vizthex123** [comment]
I've tried that too and it doesn't work.

**Comment by vizthex123** [comment]
Update: I used `minecraft:entities/boss/wither` and that finally worked. 

After like 2 months, I've finally fixed this stupid thing.
